"""add conversation table

Revision ID: 2ae1e875591f
Revises: 8bff02c4e1b7
Create Date: 2019-12-03 22:29:12.988158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae1e875591f'
down_revision = '8bff02c4e1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convo_id', sa.Integer(), nullable=True),
    sa.Column('reply', sa.String(length=255), nullable=True),
    sa.Column('posted_by', sa.String(length=255), nullable=True),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    # ### end Alembic commands ###
