"""add conversation table

Revision ID: 8bff02c4e1b7
Revises: 118285ada5df
Create Date: 2019-12-03 21:44:14.554299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bff02c4e1b7'
down_revision = '118285ada5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_id', sa.Integer(), nullable=True),
    sa.Column('convo', sa.String(length=255), nullable=True),
    sa.Column('posted_by', sa.String(length=255), nullable=True),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation')
    # ### end Alembic commands ###
